# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:        pretty

# Setup
title:            Leo Gomes
tagline:          'Open source and random things'
description:      #'These days you will mostly read about <a href="http://netty.io">Netty</a> here.'
url:              http://leogomes.github.io
paginate:         1
baseurl:          /

# About/contact
author:
  name:           Leonardo Freitas Gomes
  url:            https://twitter.com/lgomes
  email:          leonardo.f.gomes@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/leogomes

gems: [jekyll-paginate]
